# Generated by Django 4.1 on 2022-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Im',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Мессенджеры')),
            ],
            options={
                'verbose_name': 'Im',
                'verbose_name_plural': 'Ims',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон контакта')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL ресурсов контакта')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор контакта')),
                ('ADDRESS', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес контакта')),
                ('ADDRESS_CITY', models.CharField(blank=True, max_length=500, null=True, verbose_name='Город')),
                ('ADDRESS_COUNTRY', models.CharField(blank=True, max_length=500, null=True, verbose_name='Страна')),
                ('ADDRESS_COUNTRY_CODE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Код страны')),
                ('ADDRESS_POSTAL_CODE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Почтовый индекс')),
                ('ADDRESS_PROVINCE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Область')),
                ('ADDRESS_REGION', models.CharField(blank=True, max_length=500, null=True, verbose_name='Район')),
                ('ASSIGNED_BY_ID', models.IntegerField(blank=True, null=True, verbose_name='Связано с пользователем по ID')),
                ('BIRTHDATE', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
                ('COMMENTS', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
                ('HONORIFIC', models.IntegerField(blank=True, null=True, verbose_name='Вид обращения')),
                ('LAST_NAME', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('ORIGINATOR_ID', models.CharField(blank=True, max_length=500, null=True, verbose_name='Идентификатор источника данных')),
                ('ORIGIN_ID', models.CharField(blank=True, max_length=500, null=True, verbose_name='Идентификатор элемента в источнике данных')),
                ('POST', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('SOURCE_ID', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор источника')),
                ('TYPE_ID', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор типа')),
                ('UTM_CAMPAIGN', models.CharField(blank=True, max_length=500, null=True, verbose_name='Обозначение рекламной кампании')),
                ('UTM_CONTENT', models.CharField(blank=True, max_length=500, null=True, verbose_name='Содержание кампании')),
                ('UTM_MEDIUM', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип трафика')),
                ('UTM_SOURCE', models.CharField(blank=True, max_length=500, null=True, verbose_name='Рекламная система')),
                ('UTM_TERM', models.CharField(blank=True, max_length=500, null=True, verbose_name='Условие поиска кампании')),
                ('EMAIL', models.ManyToManyField(to='api_v1.email')),
                ('IM', models.ManyToManyField(to='api_v1.im')),
                ('PHONE', models.ManyToManyField(to='api_v1.phone')),
                ('WEB', models.ManyToManyField(to='api_v1.web')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор компании')),
                ('TITLE', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название')),
                ('contacts', models.ManyToManyField(to='api_v1.contacts')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
