# Generated by Django 4.1 on 2022-09-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_remove_contacts_email_remove_contacts_im_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='web',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_CITY',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_COUNTRY',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_COUNTRY_CODE',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_POSTAL_CODE',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_PROVINCE',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ADDRESS_REGION',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ASSIGNED_BY_ID',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='BIRTHDATE',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='COMMENTS',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='HONORIFIC',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='LAST_NAME',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ORIGINATOR_ID',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='ORIGIN_ID',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='POST',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='SOURCE_ID',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='TYPE_ID',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='UTM_CAMPAIGN',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='UTM_CONTENT',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='UTM_MEDIUM',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='UTM_SOURCE',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='UTM_TERM',
        ),
        migrations.DeleteModel(
            name='Im',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
